## yum install nginx -y
#  Let's download the HTML content that serves the RoboSHop Project UI and deploy under the Nginx path.
#
#  # curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
#  Deploy in Nginx Default Location.
#
#  # cd /usr/share/nginx/html
#  # rm -rf *
#  # unzip /tmp/frontend.zip
#  # mv frontend-main/* .
#  # mv static/* .
#  # rm -rf frontend-master static README.md
#  # mv localhost.conf /etc/nginx/default.d/roboshop.conf
#  Finally restart the service once to effect the changes.
#
## systemctl restart nginx


- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed


- name: Download and Unzip the Frontend content
  ansible.builtin.import_role:
    name: common
    tasks_from: download


- name: remove old Html web pages
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: copy the HTML file
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: copy roboshop reverse proxy configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: restart
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes